### ISSUE TITLE
Tách cart ra khỏi menu khi collapse (màn hình responsive)

### ISSUE THREAD

**Issue by phucledien** [luantranminh/LayoutDoAnWeb#11]
Cái Cart button đang bị dính vô cái collapsed menu. Giờ tìm cách tách nó ra hoặc có thể là chỉnh sao đó cho nó nhìn đẹp hơn

**Comment by luantranminh** [comment]
Chắc nên chỉnh lại style bằng js khi mà nó menu nó thu ra vào .
Vấn đề đang gặp phải.
![image](https://user-images.githubusercontent.com/25551568/31316972-b8de0a48-ac62-11e7-92cb-2e863724757f.png)
hoặc có thể để dễ dàng hơn, khi hiện collapse menu thì sẽ bỏ cái cart đi và thay bằng nav-item dạng 
như : Giỏ hàng (1).
