### ISSUE TITLE
Update view checkout

### ISSUE THREAD

**Issue by phucledien** [luantranminh/LayoutDoAnWeb#22]
Hiện view checkout chưa có thông tin mẫu về sản phẩm. @xuanphongtnt48 update thêm nha !

**Comment by phucledien** [comment]
#19

**Comment by phucledien** [comment]
Thêm header vào luôn nha!

**Comment by luantranminh** [comment]
T xóa header đó. t nghĩ thêm 1 nút back quay về là được rồi, khỏi header
